Обратная связь и оптимизация
htmlacademy-javascript/184629-keksobooking-25 pull request #11
Opened 2022-04-10 19:18 UTC by 13epanda

2022-04-11 21:30 UTC, 13epanda commented on js/form-add-ads.js
> -  });
В ТЗ прописано, что изменять значение цены, если меняется тип жилья (минимальное значение, становится больше, того, что прописано) нельзя. 
Поэтому пока нашла пока лишь вариант зафиксировать диапазон слайдера

2022-04-12 07:46 UTC, babtshe requested changes
Обрати внимание, по ТЗ нужно показывать не похожие объявления, а только метки полностью подходящие под фильтры. Есть смысл убрать ранжирование из результатов поиска и заменить на точное соответствие.

2022-04-12 07:46 UTC, babtshe commented on js/form-filters.js
> +};
стоит подумать как упростить эту функцию

2022-04-12 07:46 UTC, babtshe commented on js/form-filters.js
> +  }
от магии хорошо бы избавиться и отступы сделать единообразными

2022-04-13 07:09 UTC, babtshe requested changes

2022-04-13 07:09 UTC, babtshe commented on js/form-filters.js
> +    case 'middle': return (price>10000 && price<50000);
проблема с пробелами осталась и магия никуда не исчезла.

2022-04-13 07:09 UTC, babtshe commented on js/form-filters.js
>  const getGuestsRang = (guests) => {
есть смысл переименовать функцию, так как теперь она ведёт себя иначе.

2022-04-13 07:09 UTC, babtshe commented on js/form-filters.js
> +        isSuitable = false;
обрати внимание, есть такой [критерий](https://up.htmlacademy.ru/javascript/25/criteries#b23). Хорошо бы выйти из цикла сразу как только стало понятно, что элемент не подходит. От фильтра тоже можно избавиться - нам нужно проверить наличие нужных данных в массиве, для этого хватит и поиска.

2022-04-13 07:09 UTC, babtshe commented on js/form-filters.js
> +const isSuitableSimilarAds = ({offer}) => getTypeRang(offer.type)
стоит поменять название, так как мы ищем не похожие объявления, а точное соответствие.

2022-04-13 07:09 UTC, babtshe commented on js/similar.js
> +    return similarAds;
было бы неплохо что-то возвращать при любом варианте развития событий.

2022-04-13 07:14 UTC, 13epanda commented on js/form-filters.js
> +    case 'middle': return (price>10000 && price<50000);
Нужно добавить break? В чем состоит магия?

2022-04-14 07:28 UTC, babtshe approved these changes

2022-04-14 07:28 UTC, babtshe commented on js/form-filters.js
> +      if (!Array.prototype.includes.call(features, featuresList[i].value)) {
можно чуть упростить, если вызывать так:
`[].includes.call` или так `[...whateverNodeList].includes`

2022-04-14 07:28 UTC, merged