added functions for obtaining random numbers
htmlacademy-javascript/184629-keksobooking-25 pull request #2
Opened 2022-02-20 20:26 UTC by 13epanda

2022-02-20 21:05 UTC, babtshe requested changes

2022-02-20 21:05 UTC, babtshe commented on js/main.js
> +    return undefined;
судя по названию, функция должна вернуть число, а тут `undefined`. Лучше будет явно выбросить ошибку.

2022-02-20 21:05 UTC, babtshe commented on js/main.js
> +}
обе функции очень похожи. Есть ли возможность вынести повторяющиеся части кода или вообще объединить их в одну, используя параметры по умолчанию?

2022-02-20 21:05 UTC, babtshe commented on js/main.js
> +function getRandomInteger(min,max) {
Параметры функции неплохо будет отделять пробелом.

2022-02-22 16:42 UTC, 13epanda commented on js/main.js
> +    return undefined;
Вместо `return` прописать `throw new Error('...');  `будет достаточно?

2022-02-22 16:47 UTC, 13epanda commented on js/main.js
> +}
Оставляю getRandomFloat, в которую если не передавать decimal, будет по умолчанию считать его 0 и возвращать целые числа. Название поменяю на getRandomNumber

2022-02-24 10:55 UTC, babtshe approved these changes

2022-02-24 10:55 UTC, babtshe commented on js/main.js
> +function getRandomNumber(min, max, decimal) {
чтобы упростить себе жизнь, можно присвоить третьему параметру значение по умолчанию.

2022-02-24 10:55 UTC, merged