Правда или действие (часть 1)
htmlacademy-javascript/184629-keksobooking-25 pull request #7
Opened 2022-03-29 18:55 UTC by 13epanda

---
:mortar_board: [Правда или действие (часть 1)](https://up.htmlacademy.ru/javascript/25/user/184629/tasks/14)

:boom: https://htmlacademy-javascript.github.io/184629-keksobooking-25/7/

2022-03-30 08:31 UTC, babtshe requested changes

2022-03-30 08:31 UTC, babtshe commented on js/form-add-ads.js
> +  return value.length >= 30 && value.length <= 100;
ограничения на длину можно и силами html задать

2022-03-30 08:31 UTC, babtshe commented on js/form-add-ads.js
> +}
максимальная цена - константа

2022-03-30 08:31 UTC, babtshe commented on js/form-add-ads.js
> +  return `от ${minPrice[type.value]} до 100000`;
❗️

2022-03-30 08:31 UTC, babtshe commented on js/form-add-ads.js
> +  .forEach((item) => item.addEventListener('change', onTypeChange));
см [критерий](https://up.htmlacademy.ru/javascript/25/criteries#d21)

2022-03-30 08:31 UTC, babtshe commented on js/form-add-ads.js
> +};
хорошо бы найти тут закономерность, чтобы не добавлять данные для новых комнат руками каждый раз.

2022-03-30 08:31 UTC, babtshe commented on js/form-add-ads.js
> +}
стоит подумать как сделать это более понятным для пользователя и избавиться от хардкода.

2022-03-30 08:31 UTC, babtshe commented on js/form-add-ads.js
> +});
у формы всё же должна быть возможность отправиться.

2022-03-30 08:31 UTC, babtshe commented on js/form-add-ads.js
> +  price.placeholder = minPrice[this.value];
помимо плейсхолдера можно задавать минимальное значение в html, это даст возможность быстро заполнить поле стрелками.

2022-03-30 08:31 UTC, babtshe commented on js/form-add-ads.js
> +  .querySelectorAll('[name="capacity"]')
❗️

2022-03-30 08:51 UTC, 13epanda commented on js/form-add-ads.js
> +  return `от ${minPrice[type.value]} до 100000`;
Что это значит? 
Тут тоже можно добавить тогда константу

2022-03-31 07:22 UTC, babtshe requested changes

2022-03-31 07:22 UTC, babtshe commented on js/form-add-ads.js
> +  return condition1 || condition2;
Эту часть кода хорошо бы отрефакторить:

- длина строки не должна превышать 120-140 символов - это улучшает читаемость кода
- чтобы не вычислять каждый раз `parseInt` можно сложить результат в переменную и переиспользовать, тем более что есть такой критерий
- использовать число в названии переменной в большинстве случаев антипаттерн, так как не даёт никакой информации о содержимом.

2022-03-31 07:22 UTC, babtshe commented on js/form-add-ads.js
> +    : 'Гостей не может быть больше, чем комнат';
👍

2022-03-31 07:22 UTC, babtshe commented on js/form-add-ads.js
> +  }
👍

2022-03-31 12:39 UTC, 13epanda commented on js/form-add-ads.js
> +  return condition1 || condition2;
А можно заменить письменным подсчетом `firstCondition` и  `secondCondition` 
или лучше обозначить конкретнее условие `guestsMatchRooms ` и  `lonelyMultiroom`.  Или как лучше назвать эти условия?

2022-04-01 06:51 UTC, babtshe approved these changes

2022-04-01 06:51 UTC, merged

2022-04-01 06:53 UTC, babtshe commented on js/form-add-ads.js
> +  return condition1 || condition2;
Второй вариант получше. С учётом того, что в переменных будет лежать булево значение, есть смысл добавлять в название `is`, например `isRed`, `isAvailable` итд.