added message after submit form and changed timein/out
htmlacademy-javascript/184629-keksobooking-25 pull request #8
Opened 2022-04-01 18:59 UTC by 13epanda

2022-04-01 20:00 UTC, 13epanda commented on js/form-add-ads.js
> +timein.addEventListener('change',() => {
Возникала ошибка `Arrow function should not return assignment no-return-assign`
Не понимаю как это нужно прописывать правильно, поэтому решила явно прописать return.

2022-04-01 20:05 UTC, 13epanda commented on js/form-add-ads.js
> +    successMessage.addEventListener('click', () => {
Кажется, это нужно будет сделать в следующих блоках, уже после работы с сетями и базами... Поэтому пока экран сообщения быстро исчезает и не дает себя закрыть.

2022-04-02 07:11 UTC, babtshe requested changes

2022-04-02 07:11 UTC, babtshe commented on js/form-add-ads.js
> +timein.addEventListener('change',() => {
а зачем тебе тут вообще что-то возвращать? Помимо этого обрати внимание, что хорошо будет убирать обработчики на форме при деактивации, а анонимная функция для этого не подойдёт.

2022-04-02 07:11 UTC, babtshe commented on js/form-add-ads.js
> +    const errorMessage = errorMessageTemplate.cloneNode(true);
зачем искать элементы каждый раз при вызове функции, если они всегда в разметке? Тем более есть критерий на переиспользование.

2022-04-02 07:11 UTC, babtshe commented on js/form-add-ads.js
> +    });
Обработчик будет правильно убрать после закрытия попапа.

2022-04-03 06:45 UTC, babtshe requested changes

2022-04-03 06:45 UTC, babtshe commented on js/form-add-ads.js
> +};
тут обработчик тоже хорошо убрать

2022-04-03 06:45 UTC, babtshe commented on js/form-add-ads.js
> +  document.removeEventListener('keydown', onSuccessMessageEscKeydown);
👍

2022-04-03 06:45 UTC, babtshe commented on js/form-add-ads.js
> +    errorMessage.remove();
есть же уже отдельная функция для удаления попапа, почему бы её тут не вызвать?

2022-04-03 06:45 UTC, babtshe commented on js/form-add-ads.js
> +    successMessage.addEventListener('click', closeSuccessMessage);
обрати внимание на критерий по именованию обработчиков.

2022-04-03 06:45 UTC, babtshe commented on js/form-add-ads.js
> +    errorMessage.addEventListener('click', closeErrorMessage);
❗️

2022-04-04 12:40 UTC, babtshe requested changes

2022-04-04 12:40 UTC, babtshe commented on js/form-add-ads.js
> +const MAX_PRICE = 100000;
см [критерий](https://up.htmlacademy.ru/javascript/25/criteries#b10)

2022-04-04 12:40 UTC, babtshe commented on js/popup.js
> +function closeSuccessMessage () {
см [критерий](https://up.htmlacademy.ru/javascript/25/criteries#d5)

2022-04-04 12:40 UTC, babtshe commented on js/popup.js
> +function closeErrorMessage () {
❗️

2022-04-05 11:49 UTC, babtshe approved these changes

2022-04-05 11:49 UTC, merged